version: "3.8"
services:
  frontend:
    env_file:
      - .env
    image: papier-front
    build: ./docker/frontend
    container_name: papier-front
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/opt/app
    environment:
      APP_ENV: ${APP_ENV-prod}
      PUBLIC_BACKEND_URL: ${PUBLIC_BACKEND_URL-http://localhost:3000}
    depends_on:
      - backend
    networks:
      - papier_network
  backend:
    image: papier
    build: ./docker/backend
    container_name: papier
    ports:
      - 3000:3000
    volumes:
      - ./backend:/opt/app
    environment:
      APP_ENV: ${APP_ENV-prod}
      SECRET: ${SECRET-B3cm2Ehjk72bhEeAX1VS}
      DATABASE_URL : ${DATABASE_URL-"postgresql://postgres:mysecretpassword@postgres:5432/papier"}
    depends_on:
      - postgres
    networks:
      - papier_network
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD-mysecretpassword}
      POSTGRES_DB: ${DATABASE_NAME-paper}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/volumes/database:/var/lib/postgresql/data
    networks:
      - papier_network
networks:
  papier_network:
    driver: bridge
