version: "3.8"
services:
  frontend:
    env_file:
      - .env
    image: papier-front
    build: ./docker/frontend
    container_name: papier-front
    ports: 
      - 5173:5173
    volumes:
      - ./frontend:/opt/app
    environment:
      APP_ENV: ${APP_ENV-prod}
    depends_on:
      - backend
    networks:
      - papier_network
  backend:
    env_file:
      - ./backend/.env
    image: papier
    build: ./docker/backend
    container_name: papier
    ports: 
      - 3000:3000
    volumes:
      - ./backend:/opt/app
    environment:
      APP_ENV: ${APP_ENV-prod}
    depends_on:
      - postgres
    networks:
      - papier_network
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD-mysecretpassword}
      POSTGRES_DB: ${DATABASE_NAME-paper}
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - papier_network
networks:
  papier_network:
    driver: bridge 
